name: Deploy to DockerHub and Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Fazendo login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construindo a imagem Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-app .

      - name: Enviando a imagem Docker para o DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-app

      - name: Deploy para o servidor remoto
        uses: appleboy/ssh-action@master
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-app
            docker stop node-docker-app || true
            docker rm node-docker-app || true
            docker run -d --name node-docker-app -p 8087:8080 ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-app
